server:
  port: 8081
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
security:
  jwt:
    secret: ${JWT_SECRET:secret-key}
    expiration-minutes: 120
management:
  endpoints:
    web:
      exposure:
        include: health,info
