pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'leave-management-system'

include 'discovery-service'
include 'api-gateway'
include 'auth-service'
include 'leave-service'
include 'notification-service'
