server:
  port: 8761
spring:
  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.assignment: ${LOGGING_LEVEL_APP:INFO}
